### ISSUE TITLE
Add testcase for end to end testing for client and language server

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#183] opened 2021-09-09 05:56 UTC
### Problem

Currently testcase does not exit for extension

### Solution

https://code.visualstudio.com/api/working-with-extensions/testing-extension

**Comment by webknjaz** [comment] 2021-09-09 19:28
Sounds like a duplicate of #139 (or at least it's a dependency).

**Comment by webknjaz** [comment] 2021-09-13 12:55
Duplicate of #139

**Closed by webknjaz** 2021-09-13 12:55 UTC
Labels: feature, new
