### ISSUE TITLE
Add params to "Run playbook via ansible-playbook"

### ISSUE THREAD

**Issue by JeromeK13** [ansible/vscode-ansible#363] opened 2021-12-28 14:09 UTC
### Problem

Currently i don't see any documentation or way to set flags for the ansible-playbook command. Which results that u can only run the file on localhost

### Solution

Add option to set falgs like i saw in a old extension within settings.json

something like:
`ansible.ansibelplaybook.custom: "-i ..." `
etc

**Comment by webknjaz** [comment] 2022-01-31 14:13
This seems to be not hard to implement. A PR is welcome.

**Comment by JeromeK13** [comment] 2022-02-01 18:04
Alright, I will have a look if I can provide something

**Comment by priyamsahoo** [comment] 2024-01-30 11:49
Duplicate of #1042. PR is welcome.

**Closed by priyamsahoo** 2024-01-30 11:49 UTC
Labels: feature, good first issue
