### ISSUE TITLE
Autocompletion removes a line instead of completing it

### ISSUE THREAD

**Issue by maciejduk** [ansible/vscode-ansible#489] opened 2022-04-28 13:03 UTC
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

When I press enter, tab or select autocompletion line with left mouse button, the line I was currently typing disappears.

https://user-images.githubusercontent.com/97241456/165756567-4458f1ec-328f-44fc-87d6-2a9929936ef9.mov

### Extension version

0.8.1

### VS Code version

1.66.2

### Ansible Version

```shell
└─$ ansible --version                                                                                                                          127 ⨯
ansible [core 2.12.2]
  config file = /Users/maciej/.ansible/ansible.cfg
  configured module search path = ['/Users/maciej/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.3.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/maciej/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

### OS / Environment

└─$ sw_vers
ProductName:    macOS
ProductVersion: 12.3.1
BuildVersion:   21E258

└─$ ansible-lint --version
WARNING: PATH altered to include /opt/homebrew/Cellar/ansible-lint/6.0.2/libexec/bin
ansible-lint 6.0.2 using ansible 2.12.3

### Relevant log output

```shell
None available. Please let me know if there are any logs I should be providing at this stage.
```

**Comment by SROBER28** [comment] 2022-05-02 08:29
I have the same problem

**Comment by priyamsahoo** [comment] 2022-05-10 04:56
@maciejduk and @SROBER28, the ansible extension has been updated in the marketplace.
Please, let us know if the problem persists in the newer version as well.

**Comment by maciejduk** [comment] 2022-05-11 10:50
> In order for the extension to work, you need to have python and YAML extensions enabled.

To clarify, this is what I meant by "required extensions". I have only had enabled extensions required for Ansible, Ansible extension itself, and nothing else.

Are there any other environmental settings / circumstances that I could try replicate?

I have tried brand new window in an empty folder, starting brand new file, so it does not carry any project settings or is affected by git. Unfortunately the problem remains.

@SROBER28 do you still experience the same problem after the upgrade?

**Comment by zappbrannigan34** [comment] 2022-05-16 19:13
same here

**Comment by maciejduk** [comment] 2022-05-19 13:08
Hi, just an update. I am working today from the same machine, not sure what has changed but this bug has gone away. Now, upon pressing enter, the line autocompletes and cursor moves to the next line indented (as expected).

VSC:
```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:14.619Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0
```

Ansible: v0.9.0 preview


Ansible & ansible-lint:
```
└─$ ansible-lint --version
WARNING: PATH altered to include /opt/homebrew/Cellar/ansible-lint/6.0.2/libexec/bin
ansible-lint 6.0.2 using ansible 2.12.3
                                                                                                                                                                    
┌──(maciej㉿Maciej's-Maccy-Air)-[~/DevOps/ip-ansible-servicenow]
└─$ ansible --version
ansible [core 2.12.4]
  config file = /Users/maciej/.ansible/ansible.cfg
  configured module search path = ['/Users/maciej/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/5.6.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/maciej/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.1.1
  libyaml = True
```

It seems the only notable difference between my last post when the bug was occurring and today is that I must've updated ansible core package along the way.

Is there anything I can do to help your team narrow it down? Although I now suspect the issue must be quite unique combination of versions of various elements, that seem to be incompatible??

**Comment by priyamsahoo** [comment] 2022-05-23 05:40
Thanks for the update @maciejduk. Glad that the problem is gone after the update :)

**Comment by priyamsahoo** [comment] 2022-05-23 05:46
> Hi, just an update. I am working today from the same machine, not sure what has changed but this bug has gone away. Now, upon pressing enter, the line autocompletes and cursor moves to the next line indented (as expected).
> 
> VSC:
> 
> ```
> Version: 1.67.1
> Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
> Date: 2022-05-06T12:37:14.619Z
> Electron: 17.4.1
> Chromium: 98.0.4758.141
> Node.js: 16.13.0
> V8: 9.8.177.13-electron.0
> OS: Darwin arm64 21.4.0
> ```
> 
> Ansible: v0.9.0 preview
> 
> Ansible & ansible-lint:
> 
> ```
> └─$ ansible-lint --version
> WARNING: PATH altered to include /opt/homebrew/Cellar/ansible-lint/6.0.2/libexec/bin
> ansible-lint 6.0.2 using ansible 2.12.3
>                                                                                                                                                                     
> ┌──(maciej㉿Maciej's-Maccy-Air)-[~/DevOps/ip-ansible-servicenow]
> └─$ ansible --version
> ansible [core 2.12.4]
>   config file = /Users/maciej/.ansible/ansible.cfg
>   configured module search path = ['/Users/maciej/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /opt/homebrew/Cellar/ansible/5.6.0/libexec/lib/python3.10/site-packages/ansible
>   ansible collection location = /Users/maciej/.ansible/collections:/usr/share/ansible/collections
>   executable location = /opt/homebrew/bin/ansible
>   python version = 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
>   jinja version = 3.1.1
>   libyaml = True
> ```
> 
> It seems the only notable difference between my last post when the bug was occurring and today is that I must've updated ansible core package along the way.
> 
> Is there anything I can do to help your team narrow it down? Although I now suspect the issue must be quite unique combination of versions of various elements, that seem to be incompatible??

What you said is absolutely right it seems. For some combination of versions, vscode API for autocompletion that involves `insertText` does not work. To support all of this, `textEdit` is also supposed to be used, which we missed. There's a PR for this as well: https://github.com/ansible/ansible-language-server/pull/330/

Feel free to open this issue or a new one if you face a similar sort of problem with some other version combinations even after the following PR is merged and released!

**Closed by priyamsahoo** 2022-05-23 05:46 UTC
Labels: bug, needs_info
