### ISSUE TITLE
ARM64 creator-ee images

### ISSUE THREAD

**Issue by kmf** [ansible/vscode-ansible#646] opened 2022-10-05 11:47 UTC
### Summary

Using this on an M1/ARM64 Mac would love to use a ARM64  `creator-ee` container

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 

### Extension version

v0.14.71

### VS Code version

1.71.2

### Ansible Version

```shell
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/Users/kmf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/kmf/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.7 (main, Sep 14 2022, 22:38:23) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS Monterey 12.6

**Comment by ssbarnea** [comment] 2022-10-05 18:00
Duplicate of https://github.com/ansible/creator-ee/issues/7

**Closed by ssbarnea** 2022-10-05 18:00 UTC
Labels: bug, new
