### ISSUE TITLE
Missing property "include_vars" on block:

### ISSUE THREAD

**Issue by anshibanov** [ansible/vscode-ansible#303] opened 2021-11-10 04:12 UTC
### Summary

In my playbook i have highlited stiring block: with error "Missing property "include_vars" (see screenshot). But I don't understand what error the validator is talking about

![image](https://user-images.githubusercontent.com/36153311/141047925-e12c556a-5c6f-4035-873d-f32a627d356f.png)

When i click on hyperlink "Jump to schema"

```
{
  "description": "Auto-Generated JSON Schema for Ansible-stable 2.9 (https://github.com/shaded-enmity/ansible-schema-generator)",
  "title": "Ansible 2.9",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
      "anyOf": [
        {
            "name": {
              "type": "string"
            },
            "include_vars": {
              "type": "string"
            },
```

### Extension version

v0.6.1

### VS Code version

1.62

### Ansible Version

```shell
ansible [core 2.11.6] 
  config file = /home/orange/ansible/ansible.cfg
  configured module search path = ['/home/orange/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/orange/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/orange/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/orange/.local/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.2
  libyaml = True
```

### OS / Environment

Ubuntu 20.04

**Comment by webknjaz** [comment] 2021-11-12 16:25
This version of the extension does not use json-schema anymore. You're probably hitting another one (like YAML ext).
It's most likely a duplicate of https://github.com/ansible/vscode-ansible/issues/293#issuecomment-963072533 — the language for your open document is not `Ansible` but something else and it gets handled by some other VS Code extension. You can change that manually.

**Comment by anshibanov** [comment] 2021-11-14 06:16
You right. Thank you

**Closed** 2021-11-14 06:16 UTC
Labels: new, needs_info
