### ISSUE TITLE
Latest version breaks Copilot tab autocompletion

### ISSUE THREAD

**Issue by binaryfire** [ansible/vscode-ansible#1108] opened 2024-02-28 07:07 UTC
### Summary

Copilot suggestions can no longer be tab-autocompleted in yaml files when the latest version of this extension is active. Rolling back to v2.10.130 fixed the problem.

### Extension version

v2.12.143

### VS Code version

1.86.2

### OS / Environment

Windows 11 - WSL2 (Ubuntu 22.04)

**Comment by ssbarnea** [comment] 2024-02-28 14:11
@TamiTakamiya Do you know anything about this?

**Comment by TamiTakamiya** [comment] 2024-02-28 18:43
I could not locate any major changes in handling tab key in our latest version, but could recreate the issue:

* With v2.10 installed
https://github.com/ansible/vscode-ansible/assets/27698807/403ba189-faa8-4f90-a909-529a80d5fb9d

* With v2.12 installed
https://github.com/ansible/vscode-ansible/assets/27698807/3c4daf63-740d-4647-b69e-3ee4a33e8ec6

**Comment by TamiTakamiya** [comment] 2024-02-28 18:59
I thnk it is caused by the change we made with #1099.  It was for suppressing duplicated feedbacks for suggestions made by Lightspeed, but it suppressed the commit commands as well when no pending Lightspeed suggestions, to which feedback is sent.  If the suggestion is provided by other providers, we should suppress feedbacks, but still need to send the commit command.

**Comment by slawo** [comment] 2024-03-02 15:23
Same issue, no more tabs with copilot.

**Comment by juanvalino** [comment] 2024-03-06 09:16
Same problem here.

**Comment by pschiffe** [comment] 2024-03-06 16:20
Seems to be fixed for me, thank you!

**Comment by TamiTakamiya** [comment] 2024-03-12 17:02
@pschiffe Thanks for your feedback. I am going to close this issue.

**Closed by TamiTakamiya** 2024-03-12 17:02 UTC
Labels: bug
