### ISSUE TITLE
(archlinux): Ansible could not initialize the preferred locale: unsupported locale setting

### ISSUE THREAD

**Issue by orblazer** [ansible/vscode-ansible#690] opened 2022-11-20 10:34 UTC
### Summary

When i open ansible files, is right highlighted but throw the following error.

In Status bar i have `Ansible info` in red with this message :
![Screenshot_20221120_113030](https://user-images.githubusercontent.com/1344792/202897221-de3b9809-c808-4d2d-9a79-4846b84ad6ce.png)

### Extension version

1.0.90 (and tried 1.0.98)

### VS Code version

VSCodium 1.73.1 (release 22314)

### Ansible Version

```shell
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/orblazer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/orblazer/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Linux, 5.15.78-1-MANJARO
ansible-lint 6.8.6 using ansible 2.14.0

### Relevant log output

```shell
cmd 'ansible-lint --version' was not executed with the following error: ' Error: Command failed: ansible-lint --version
Unable to find a working copy of ansible executable.

[Info  - 11:16:34 AM] [ansible-lint] ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 319, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 214, in main
    app = get_app(offline=options.offline)
  File "/usr/lib/python3.10/site-packages/ansiblelint/app.py", line 325, in get_app
    app = App(options=default_options)
  File "/usr/lib/python3.10/site-packages/ansiblelint/app.py", line 47, in __init__
    self.runtime = Runtime(isolated=True)
  File "/usr/lib/python3.10/site-packages/ansible_compat/runtime.py", line 96, in __init__
    self.config = AnsibleConfig()
  File "/usr/lib/python3.10/site-packages/ansible_compat/config.py", line 422, in __init__
    config_dump = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ansible-config', 'dump']' returned non-zero exit status 1.

[Error - 11:16:34 AM] An error occurred in 'onDidOpen' handler: [TypeError] Cannot read properties of undefined (reading 'has')
TypeError: Cannot read properties of undefined (reading 'has')
    at /home/orblazer/.vscode-oss/extensions/redhat.ansible-1.0.98-universal/out/server/src/server.js:2:44793
    at Generator.next (<anonymous>)
    at s (/home/orblazer/.vscode-oss/extensions/redhat.ansible-1.0.98-universal/out/server/src/server.js:2:42432)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ssbarnea** [comment] 2022-11-20 23:13
I think that you might have a local configuration issue:
```
Ansible could not initialize the preferred locale: unsupported locale setting
```
Are you able to properly run `ansible-config dump` from your terminal and also from your vscode terminal?

I might also be useful to post result of running `set|grep -E LANG\|LC_` so we would know which locale you have configured that does not work.

To me this looks like same false-bug from https://github.com/ansible/ansible/issues/78283

Still, I will not close this issue because if adding specific locales such those mentioned on https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/porting_guides/porting_guide_core_2.14.rst#id4 we might be able to add them ourselves and save few folks from encountering this issue.

**Comment by orblazer** [comment] 2022-11-21 10:38
Hello,

This is output of CMDs:
- `ansible-config dump` : https://gist.github.com/orblazer/05e6d5f4736d5e6b75803ed1dafa901b
- `set|grep -E LANG\|LC_` :

    ```sh
    LANG=en_US.UTF-8
    LC_ADDRESS=fr_FR.UTF-8
    LC_ALL=en_US.UTF-8
    LC_IDENTIFICATION=fr_FR.UTF-8
    LC_MEASUREMENT=fr_FR.UTF-8
    LC_MONETARY=fr_FR.UTF-8
    LC_NAME=fr_FR.UTF-8
    LC_NUMERIC=fr_FR.UTF-8
    LC_PAPER=fr_FR.UTF-8
    LC_TELEPHONE=fr_FR.UTF-8
    LC_TIME=en_150.UTF-8 # This is for have french format
    ```

This is also weird because if i run the following command (output from vscode notification) directly in the vscode terminal i don't have any issues.
```sh
ansible-lint --offline --nocolor -f codeclimate "./main.yaml"
```

**Comment by ssbarnea** [comment] 2022-11-21 13:19
Are you using execution-environments by any chance with vscode extension? If you do it might explain why it fails as container engine might pass some of the locale senttings to the container and the container does not have them installed so it fails.

**Comment by orblazer** [comment] 2022-11-23 13:06
No, i never configure some execution-environments in vscode.

**Comment by ssbarnea** [comment] 2022-11-23 14:16
If you can reproduce this on a mainstream distribution rhel/centos/fedora/ubuntu/debian/wsl, we can fix it, if not we will likely close it as wontfix.

We would obviously accept a patch it if does not break supported platforms.

**Comment by ssbarnea** [comment] 2022-11-23 18:21
@orblazer Does running `LC_TIME=en_150.UTF-8 ansible-config dump` work? Originally you reported that it was working but I have some doubts.

**Closed** 2022-11-23 22:29 UTC
Labels: bug

**Comment by orblazer** [comment] 2022-11-24 10:05
Yes this is work fine :thinking: that is strange, but i have no longer the issue after i have change `LC_TIME`.

**Comment by ssbarnea** [comment] 2022-11-24 10:27
If you spot a case where only the extension fails but you can call ansible from your terminal and works fine, mention me as this would count as a high priority bug. Probably it worked with ansible 2.13, but in 2.14 that special check for valid locale settings was added, so we would ensure that the tool is working fine. 

That means that with 2.13 you would not have known that some bits might not work well due to your locale, giving you the impression that all is ok.

**Comment by whysthatso** [comment] 2022-12-20 14:25
@ssbarnea i seem to run into this problem, but i do not have any weird locale settings afaik.

`locale` output

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

ansible --version
```
ansible [core 2.14.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

vscodium-bin on arch linux
```
Version: 1.74.1
Release: 22349
Commit: 13a0ba2641013eb7486bd33a6fa1f0b693177836
Date: 2022-12-15T18:22:01.285Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.12-zen1-1-zen
Sandboxed: No
```

**Comment by whysthatso** [comment] 2023-01-19 12:54
i could not debug this issue further, as i was not able to figure out what locale the ansible extension actually utilizes.
however, i followed the rather crude advice in https://github.com/microsoft/vscode/issues/62623:
1. uninstall ansible and python extensions
2. quit vscodium
3. start vscodium
4. reinstall both extensions
5. quit and restart once more

now the error message disappears and ansible extension works as expected.

#ihatecomputers

**Comment by whysthatso** [comment] 2023-02-02 17:05
so it seems this was related to my kde plasmasession locale settings. i had set some European specific things, like currency format, metric system, etc. i've reverted them all to default, which fixed the problem.

alternativly you can start vscode / vscodium like so:
`LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 ` which also fixed it

to figure out what locale your desktop session runs check `/proc/(pid of i.e. plasmashell)/environ`

**Comment by whysthatso** [comment] 2023-02-03 13:32
i found my culprit: ~/.config/plasma-localerc had set LANG=en_150.UTF-8

**Comment by tabish-javed** [comment] 2023-06-03 12:19
@ssbarnea - I have exactly same problem running ansible command inside vscode terminal connected to container ansible installed in. However, when I attach to container's shell without vscode it works fine. I compared environments in-fact vscode pushes many environment variables. 

Could you help me with... configuring vscode not to push it's environment when opening/connecting to container.

**Comment by PCBismarck** [comment] 2023-07-21 08:09
> @ssbarnea - I have exactly same problem running ansible command inside vscode terminal connected to container ansible installed in. However, when I attach to container's shell without vscode it works fine. I compared environments in-fact vscode pushes many environment variables.
> 
> Could you help me with... configuring vscode not to push it's environment when opening/connecting to container.

I notice that the langue in my docker desktop is **POSIX**, but when I use vscdoe container to run it, i found i became **en_US.UTF-8**, so i just install the en language package and it works well
i use this command to install the package
`apt install language-pack-en`
