### ISSUE TITLE
Auto Completion missing command and shell modules

### ISSUE THREAD

**Issue by yoshiotobe** [ansible/vscode-ansible#184] opened 2021-09-09 09:51 UTC
### Summary

When trying to use an auto completion, it does not show command nor shell moduels.
It does show other modules such as apt, copy, file, etc.
I use them often. So, it would be helpful if they appear in the selection.

### Extension version

0.4.5

### VS Code version

1.60.0

### Ansible Version

```shell
ansible [core 2.11.2]
  config file = /home/ubuntu/venv/heart-ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/venv/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### OS / Environment

Windows 10, WSL (Ubuntu 20.04), ansible-lint 5.0.12

![command](https://user-images.githubusercontent.com/38850403/132663551-2440d55d-59d4-476d-a393-390f5fd4c464.jpg)

![shell](https://user-images.githubusercontent.com/38850403/132663651-fc72c2cc-77aa-4220-b02d-d8a3916ba871.jpg)

**Comment by webknjaz** [comment] 2021-09-09 18:17
Is this a duplicate of #174?

**Comment by yoshiotobe** [comment] 2021-09-10 02:10
It's similar, but #174 reports an entire auto completion does not work.
In my case, auto completion works, but only command and shell are not working.
That's why I made this as a different issue.

I tried it again and noticed something.
The command and shell appear in the selection if I don't type anything after a name such as below.

\- name:
     command and shell appear

\- name: type something here
   command and shell does not appear

**Comment by webknjaz** [comment] 2021-09-13 12:46
Hey @yoshiotobe, did you use the `redhat.ansible` extension or the old one (`zbr.ansible` — did you uninstall this one?). Also, please, check what language is assigned to your task files? There is a good chance that you may be using the wrong version.

**Comment by ssbarnea** [comment] 2021-09-13 12:52
Also please take a look at #158 and report if you also seen that error because that bug would have a side effect of breaking auto-complete.

**Comment by yoshiotobe** [comment] 2021-09-15 04:30
Thank you for your replies.
I'm using redhat.ansible not zbr.ansible extension. 
I'm not manually associating tasks files with any language. So, I suppose VSCode detects them automatically.
 I looked at #158 but don't understand it. Sorry for that.

**Closed** 2023-02-07 10:51 UTC
Labels: bug, needs_info
